### ISSUE TITLE
Make create_timecapsule fails

### ISSUE THREAD

**Issue by yangm97** [joemiller/docker-htpc#2]
```
yan@Pobrebook:~/docker-htpc$ make create_timecapsule 
Error response from daemon: invalid subinterface vlan name br0, example formatting is eth0.10
Makefile:25: recipe for target '_configure_network' failed
make: *** [_configure_network] Error 1
```

**Comment by joemiller** [comment]
`br0` is my server's primary interface, yours may be `eth0` or something else. Update the makefile and set `NETWORK_IFACE` to yours. https://github.com/joemiller/docker-htpc/blob/master/Makefile#L20

That might be the issue. If not, please let me know, I am curious. I recall seeing a similar issue during testing but I think that was with one of the other docker network drivers.

**Comment by yangm97** [comment]
I thought br0 was the interface being created, still changing the br0 to the ethernet interface solved the issue. I haven't tried backing up yet but it shows a nice time capsule icon on Finder. 

I really liked the idea of having ahavi inside a container but does it need to be inside a bridged network to work or you made it like this so it would better fit your needs? Also, I found interesting the use of Makefiles for creating the containers, do you think it's better than docker-compose?

**Comment by joemiller** [comment]
I create a docker "network" on the main ethernet interface of the server so that the timecapsule container can "appear" on the network without having to share the host's IP address and map ports. This lets the container appear on the network and obtain its own IP addresses on the local LAN much like a VM in bridged mode could do. In my setup I only use ipv6 for the container. This is because the docker containers are able to obtain a valid ipv6 address from the network/router using SLAAC. You cannot currently obtain an ipv4 address via dhcp in this mode. Instead you need to create a range of available ipv4 addrs when the docker-network-create cmd runs. For my needs, ipv6 was plenty and has worked out very well actually.

I have an actual globally routable ipv6 range on my network and the container is able to acquire an address from this range. However, I suspect it would work fine if the container and the clients on the LAN only had link-local `fe80::*` addresses available, since this seems to work generally well for other apple products on LANs.

 I went with this setup specifically because I already had an instance of samba running on the host and sharing out a variety of directories (`/files/{movies,music,tv_shows}` etc) and I didn't want to try to build a single samba server config that hosted all of those directories as well as the `timemachine` export.

I'm sure it could be done a more standard way. For example, you could probably go the more traditional docker route and map ports from the host into the container (the ports that need to be mapped should be listed in the timecapsule/Dockerfile). But for the avahi/mDNS announcements (which I believe may be required) would probably need to come from an avahi instance running on the host instead of inside the container. Or perhaps you could configure avahi inside the container to send mDNS announcements containing the IP of the host instead of the IP assigned to the docker container.

Of course, running the container with host networking would probably work the simplest too.

As for using the container as a more general samba instance that shares out other directories besides the timecapsule directory, there may be some tweaks needed. Since I have added a `dfree` script to report a lower available disk space to timemachine, the current setup may need some tweaking since that script only assumes a single `/timemachine` directory is being shared.

Also I was afraid that adding anything else to the config would break timemachine, since this patch is very new and not widely tested (as of late 2016).
